stages:
  - validate
  - release

default:
  image: rust:latest
  before_script:
    - rustup component add rustfmt clippy

fmt:
  stage: validate
  script:
    - cargo fmt --all -- --check

clippy:
  stage: validate
  script:
    - cargo clippy --all-targets --all-features -- -D warnings

test:
  stage: validate
  script:
    - cargo test --all-targets --all-features

.release_job:
  stage: release
  rules:
    - if: '$CI_COMMIT_TAG'
      when: on_success
    - when: manual
  allow_failure: true
  artifacts:
    expire_in: 7 days

build_release_amd64_linux:
  extends: .release_job
  script:
    - VERSION=${CI_COMMIT_TAG#v:-dev}
    - TARGET=x86_64-unknown-linux-gnu
    - cargo build --release --locked --bin parley
    - mkdir -p dist/$TARGET
    - cp target/release/parley dist/$TARGET/parley
    - cd dist/$TARGET
    - sha256sum parley > parley.sha256
    - tar -czvf parley-${VERSION}-linux-x86_64.tar.gz parley parley.sha256
  artifacts:
    paths:
      - dist/x86_64-unknown-linux-gnu/parley-*.tar.gz
    expire_in: 7 days

build_release_aarch64_linux:
  extends: .release_job
  script:
    - VERSION=${CI_COMMIT_TAG#v:-dev}
    - TARGET=aarch64-unknown-linux-gnu
    - cargo build --release --locked --bin parley
    - mkdir -p dist/$TARGET
    - cp target/release/parley dist/$TARGET/parley
    - cd dist/$TARGET
    - sha256sum parley > parley.sha256
    - tar -czvf parley-${VERSION}-linux-aarch64.tar.gz parley parley.sha256
  artifacts:
    paths:
      - dist/aarch64-unknown-linux-gnu/parley-*.tar.gz
    expire_in: 7 days

build_release_aarch64_macos:
  extends: .release_job
  tags:
    - macos
    - arm64
  before_script:
    - rustup component add rustfmt clippy
  script:
    - VERSION=${CI_COMMIT_TAG#v:-dev}
    - TARGET=aarch64-apple-darwin
    - cargo build --release --locked --bin parley
    - mkdir -p dist/$TARGET
    - cp target/release/parley dist/$TARGET/parley
    - cd dist/$TARGET
    - shasum -a 256 parley > parley.sha256
    - tar -czvf parley-${VERSION}-macos-aarch64.tar.gz parley parley.sha256
  artifacts:
    paths:
      - dist/aarch64-apple-darwin/parley-*.tar.gz
    expire_in: 7 days
